# permissions to be able to apply templates for appstudio tier
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: appstudio-pipelines-runner
rules:
- apiGroups:
  - tekton.dev
  resources:
  - pipelineruns
  verbs:
  - get
  - list
  - update
  - patch
- apiGroups:
  - tekton.dev
  resources:
  - taskruns
  verbs:
  - get
  - patch
- apiGroups:
  - tekton.dev
  resources:
  - taskruns/status
  verbs:
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - create
  - patch
  - delete
- apiGroups:
  - sharedresource.openshift.io
  resourceNames:
  - redhat-appstudio-user-workload
  resources:
  - sharedsecrets
  verbs:
  - use
- apiGroups:
  - security.openshift.io
  resourceNames:
  - csi-scc
  - appstudio-pipelines-scc
  resources:
  - securitycontextconstraints
  verbs:
  - use
- apiGroups:
  - appstudio.redhat.com
  resources:
  - enterprisecontractpolicies
  verbs:
  - get
  - list
