apiVersion: template.openshift.io/v1
kind: Template
metadata:
  labels:
    provider: codeready-toolchain
    project: codeready-toolchain
  name: basic-dev
objects:
  - apiVersion: v1
    kind: Namespace
    metadata:
      labels:
        provider: codeready-toolchain
        project: codeready-toolchain
      name: ${USERNAME}-dev
  - apiVersion: authorization.openshift.io/v1
    kind: RoleBinding
    metadata:
      labels:
        provider: codeready-toolchain
        app: codeready-toolchain
      name: user-edit
      namespace: ${USERNAME}-dev
    roleRef:
      name: edit
    subjects:
      - kind: User
        name: ${USERNAME}
    userNames:
      - ${USERNAME}
parameters:
  - name: USERNAME
    value: johnsmith