---
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  labels:
    provider: codeready-toolchain
    project: codeready-toolchain-user
    version: ${COMMIT}
  name: codeready-toolchain-user
objects:
- apiVersion: project.openshift.io/v1
  kind: ProjectRequest
  metadata:
    annotations:
      openshift.io/description: ${PROJECT_NAME}
      openshift.io/display-name: ${PROJECT_NAME}
      openshift.io/requester: ${PROJECT_REQUESTING_USER}
    labels:
      provider: codeready-toolchain
      project: codeready-toolchain-user
      version: ${COMMIT}
    name: ${PROJECT_NAME}
- apiVersion: authorization.openshift.io/v1
  kind: RoleBinding
  metadata:
    labels:
      app: codeready-toolchain-user
      provider: codeready-toolchain
      version: ${COMMIT}
    name: user-admin
    namespace: ${PROJECT_NAME}
  roleRef:
    name: admin
  subjects:
  - kind: User
    name: ${ADMIN_USER_NAME}
  # userNames:
  # - ${USER_NAME}
parameters:
- name: PROJECT_NAME
- name: ADMIN_USER_NAME
- name: PROJECT_REQUESTING_USER
  value: system:admin
- name: COMMIT
  value: 123abc