apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: workspace-lister
rules:
- apiGroups:
  - toolchain.dev.openshift.com
  resources:
  - workspaces
  verbs:
  - get
  - list
