# See https://catalog.redhat.com/software/containers/ubi8/nodejs-16/615aee9fc739c0a4123a87e1?container-tabs=dockerfile
# FROM registry.access.redhat.com/ubi8/nodejs-16 AS build
FROM registry.access.redhat.com/ubi8/ubi:latest

LABEL maintainer "Devtools <devtools@redhat.com>"
LABEL author "Devtools <devtools@redhat.com>"

ENV NODEJS_VERSION=16 \
    NPM_RUN=start \
    NAME=nodejs \
    NPM_CONFIG_PREFIX=$HOME/.npm-global \
    PATH=$HOME/node_modules/.bin/:$HOME/.npm-global/bin/:$PATH

RUN yum -y module enable nodejs:$NODEJS_VERSION && \
    MODULE_DEPS="make gcc gcc-c++ libatomic_ops git openssl-devel" && \
    INSTALL_PKGS="$MODULE_DEPS nodejs npm nodejs-nodemon nss_wrapper" && \
    ln -s /usr/lib/node_modules/nodemon/bin/nodemon.js /usr/bin/nodemon && \
    ln -s /usr/libexec/platform-python /usr/bin/python3 && \
    yum install -y --setopt=tsflags=nodocs $INSTALL_PKGS && \
    rpm -V $INSTALL_PKGS && \
    node -v | grep -qe "^v$NODEJS_VERSION\." && echo "Found VERSION $NODEJS_VERSION" && \
    yum -y clean all --enablerepo='*'

ADD . /opt/app-root/src
WORKDIR /opt/app-root/src
RUN whoami
RUN rm -f /opt/app-root/dist/*
RUN node --version
RUN npm i -g corepack
RUN which yarn
RUN yarn install && yarn build
RUN cp -r dist/* /opt/app-root/dist
RUN ls -l /opt/app-root/dist