apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "toolchain.dev.openshift.com/v1alpha1",
          "kind": "NSTemplateSet",
          "metadata": {
            "labels": {
              "username": "johnsmith"
            },
            "name": "johnsmith"
          },
          "spec": {
            "namespaces": [
              {
                "revision": "ab12ef",
                "type": "ide"
              },
              {
                "revision": "34efcd",
                "type": "cicd"
              },
              {
                "revision": "cdef56",
                "type": "stage"
              }
            ],
            "tierName": "basic"
          }
        },
        {
          "apiVersion": "toolchain.dev.openshift.com/v1alpha1",
          "kind": "UserAccount",
          "metadata": {
            "name": "johnsmith",
            "namespace": "toolchain-member-operator"
          },
          "spec": {
            "nsLimit": "admin",
            "nsTemplateSet": {
              "namespaces": [
                {
                  "revision": "34efcd",
                  "type": "dev"
                },
                {
                  "revision": "ab12ef",
                  "type": "code"
                },
                {
                  "revision": "cdef56",
                  "type": "stage"
                }
              ],
              "tierName": "basic"
            },
            "userID": "1a03ecac-7c0b-44fc-b66d-12dd7fb21c40"
          }
        }
      ]
    capabilities: Basic Install
  name: member-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: UserAccount keeps all information about user provisioned in the
        cluster
      displayName: UserAccount
      kind: UserAccount
      name: useraccounts.toolchain.dev.openshift.com
      version: v1alpha1
    - description: NSTemplateSet defines user environment via templates that are used
        for namespace provisioning
      displayName: NSTemplateSet
      kind: NSTemplateSet
      name: nstemplatesets.toolchain.dev.openshift.com
      version: v1alpha1
  description: Placeholder description
  displayName: Member Operator
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - ""
          resources:
          - nodes
          verbs:
          - list
        - apiGroups:
          - ""
          resources:
          - namespaces
          verbs:
          - get
          - create
          - update
          - list
          - watch
        - apiGroups:
          - user.openshift.io
          resources:
          - identities
          - users
          - useridentitymappings
          - groups
          verbs:
          - get
          - create
          - update
          - list
          - watch
          - delete
        - apiGroups:
          - core.kubefed.k8s.io
          resources:
          - kubefedclusters
          verbs:
          - '*'
        - apiGroups:
          - toolchain.dev.openshift.com
          resources:
          - '*'
          verbs:
          - '*'
        - apiGroups:
          - rbac.authorization.k8s.io
          - authorization.openshift.io
          resources:
          - rolebindings
          verbs:
          - get
          - list
          - watch
          - create
          - update
        - apiGroups:
          - rbac.authorization.k8s.io
          - authorization.openshift.io
          resources:
          - clusterroles
          verbs:
          - '*'
        - apiGroups:
          - apiextensions.k8s.io
          resources:
          - customresourcedefinitions
          verbs:
          - get
          - create
          - list
          - watch
        serviceAccountName: member-operator
      deployments:
      - name: member-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: member-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: member-operator
            spec:
              containers:
              - command:
                - member-operator
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: member-operator
                image: REPLACE_IMAGE
                imagePullPolicy: IfNotPresent
                name: member-operator
                resources: {}
              serviceAccountName: member-operator
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - '*'
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - '*'
        - apiGroups:
          - apps
          resourceNames:
          - member-operator
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - core.kubefed.k8s.io
          resources:
          - kubefedclusters/status
          verbs:
          - update
        serviceAccountName: member-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  maturity: alpha
  provider: {}
  version: 0.0.1
