apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: nstemplatesets.toolchain.dev.openshift.com
spec:
  additionalPrinterColumns:
  - JSONPath: .spec.tierName
    name: Tier Name
    type: string
  - JSONPath: .status.conditions[?(@.type=="Ready")].status
    name: Ready
    type: string
  - JSONPath: .status.conditions[?(@.type=="Ready")].reason
    name: Reason
    type: string
  group: toolchain.dev.openshift.com
  names:
    kind: NSTemplateSet
    plural: nstemplatesets
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            namespaces:
              description: The namespace templates +listType
              items:
                properties:
                  revision:
                    description: The revision of the corresponding template
                    type: string
                  template:
                    description: Optional field. Used to specify a custom template
                    type: string
                  type:
                    description: 'The type of the namespace. For example: ide|cicd|stage|default'
                    type: string
                required:
                - type
                - revision
                type: object
              type: array
            tierName:
              description: The name of the tier represented by this template set
              type: string
          required:
          - tierName
          - namespaces
          type: object
        status:
          properties:
            conditions:
              description: 'Conditions is an array of current NSTemplateSet conditions
                Supported condition types: ConditionReady +patchMergeKey=type +patchStrategy=merge
                +listType'
              items:
                properties:
                  lastTransitionTime:
                    description: Last time the condition transit from one status to
                      another.
                    format: date-time
                    type: string
                  message:
                    description: Human readable message indicating details about last
                      transition.
                    type: string
                  reason:
                    description: (brief) reason for the condition's last transition.
                    type: string
                  status:
                    description: Status of the condition, one of True, False, Unknown.
                    type: string
                  type:
                    description: Type of condition
                    type: string
                required:
                - type
                - status
                type: object
              type: array
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
