kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: member-operator
subjects:
- kind: ServiceAccount
  name: member-operator
  namespace: toolchain-member-operator
roleRef:
  kind: ClusterRole
  name: member-operator
  apiGroup: rbac.authorization.k8s.io
