kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: member-operator
subjects:
- kind: ServiceAccount
  name: member-operator
  # Replace this with the namespace in which the operator will be deployed
  namespace: REPLACE_NAMESPACE
roleRef:
  kind: ClusterRole
  name: member-operator
  apiGroup: rbac.authorization.k8s.io
