apiVersion: template.openshift.io/v1
kind: Template
metadata:
  labels:
    provider: codeready-toolchain
    project: codeready-toolchain
  name: basic-code
objects:
  - apiVersion: v1
    kind: Namespace
    metadata:
      labels:
        provider: codeready-toolchain
        project: codeready-toolchain
      name: ${USER_NAME}-code
  - apiVersion: authorization.openshift.io/v1
    kind: RoleBinding
    metadata:
      labels:
        provider: codeready-toolchain
        app: codeready-toolchain
      name: user-edit
      namespace: ${USER_NAME}-code
    roleRef:
      name: edit
    subjects:
      - kind: User
        name: ${USER_NAME}
    userNames:
      - ${USER_NAME}
parameters:
  - name: USER_NAME
    value: johnsmith
