FROM registry.access.redhat.com/ubi7-dev-preview/ubi-minimal:latest

LABEL maintainer "Devtools <devtools@redhat.com>"
LABEL author "Devtools <devtools@redhat.com>"

ENV LANG=en_US.utf8

COPY member-operator /usr/local/bin/member-operator
USER 10001

ENTRYPOINT [ "/usr/local/bin/member-operator" ]
