name: govulncheck
on:
  pull_request:
    branches:
      - master

jobs:
  govulncheck:
    name: govulncheck
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod

    - name: Generate Assets
      run: |
        make generate-assets

    - name: Debug
      run: |
        ls -R pkg/autoscaler

    - name: Run govulncheck
      uses: golang/govulncheck-action@v1
      with:
        go-version-input: 1.22.12
        go-package: ./...